# manually changes happen here

base: 
  project: aschonn-mlops-project
  random_state: 35
  target_col: TARGET

data_source:
  s3_source: data_given/winequality.csv

load_data:
  raw_dataset_csv: data/raw/winequality.csv

split_data: 
  training_path: data/processed/train_winequality.csv
  test_path: data/processed/test_winequality.csv
  test_size: .2


estimators:
  ElisticNet:
    params:
      alpha: 0.88
      l1_ratio: 0.89

model_dir: saved_models
